service: aws-node-rest-api

custom:
  settings:
   #SECRET_VALUE: ${ssm:/kms-test/value1}
   SECRET_VALUE: ${ssm:/kms-test/value1~true}

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: us-east-1
  environment: ${self:custom.settings}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  kms:  
    handler: kms.kms
    events:
      - http:
          path: / 
          method: get
